{
 "title": "🚀 OTA Server Ultimate Metrics Dashboard",
 "tags": [
  "oss",
  "metrics",
  "ota-server"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROM", "label": "Data Source", "query": "prometheus" },
   {
    "name": "platform",
    "label": "Platform",
    "query": "label_values(active_users_total, platform)"
   },
   {
    "name": "runtime",
    "label": "Runtime",
    "query": "label_values(active_users_total, runtime)"
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": "label_values(active_users_total, branch)"
   },
   {
    "name": "update",
    "label": "Update",
    "query": "label_values(active_users_total, update)"
   }
  ]
 },
 "panels": [
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "🟢 Total Unique Active Users (4h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(\n  sum by (instance) (global_active_users_total)\n)",
     "legendFormat": "Total Unique Active Users"
    }
   ]
  },
  {
   "title": "📊 Unique Active Users by Runtime And Update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (runtime, update) (\n  sum by (platform, runtime, branch, update, instance) (\n    active_users_total{platform=~\"$platform\", runtime=~\"$runtime\", branch=~\"$branch\", update=~\"$update\"}\n  )\n)",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "📊 Unique Active Users by Platform",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (platform) (\n  sum by (platform, instance) (\n    global_active_users_total{platform=~\"$platform\"}\n  )\n)",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "🚨 Fatal error per update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(update_error_users_total{platform=~\"$platform\", runtime=~\"$runtime\", branch=~\"$branch\", update=~\"$update\"})\n  by (update)",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "🚨 Update error users total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(update_error_users_total{platform=~\"$platform\", runtime=~\"$runtime\", branch=~\"$branch\", update=~\"$update\"})",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  { "title": "Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "⬇️ Total Update Downloads by Update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(update_downloads_total{platform=~\"$platform\", runtime=~\"$runtime\", branch=~\"$branch\", update=~\"$update\"}) by (update)",
     "legendFormat": "{{update}}"
    }
   ]
  },
  {
   "title": "⬇️ Total Update Downloads by Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(update_downloads_total{platform=~\"$platform\", runtime=~\"$runtime\", branch=~\"$branch\", update=~\"$update\"}) by (runtime)",
     "legendFormat": "{{update}}"
    }
   ]
  },
  {
   "title": "⚡ Update Downloads Rate Over Time by Runtime & Update",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (update, runtime) (update_downloads_total{platform=~\"$platform\", runtime=~\"$runtime\", branch=~\"$branch\", update=~\"$update\", updateType=~\"$updateType|.*\"})",
     "legendFormat": "{{updateType}}"
    }
   ]
  }
 ]
}